const menuList = [
    {
        title:'账号管理',
        key:'/account',
        children:[
            {
                title:'用户账号',
                key:'/main/account/user',
            },
            {
                title:'管理员账号',
                key:'/main/account/admin',
            },
        ]
    },
    {
        title:'新闻信息',
        key:'/news',
        children:[
            {
                title:'新闻分类',
                key:'/main/news/classification',
            },
            {
                title:'新闻内容',
                key:'/main/news/content',
            }
        ]
    },
    {
        title:'标签管理',
        key:'/main/label',
    },
    {
        title:'个人中心',
        key:'/main/personal'
    },
];
export default menuList;